
autogenerated=simpletrack/common/particle.h simpletrack/opencl/particlecl.h


autogen: $(autogenerated)
	code_gen.py -i simpletrack/common/particle.h
	code_gen.py -i simpletrack/opencl/particlecl.h

